export const ADD_CONTACT = 'ADD_CONTACT';
export const LOAD_CONTACTS_SUCCESS = 'LOAD_CONTACTS_SUCCESS';
export const LOAD_CONTACTS_FAILURE = 'LOAD_CONTACTS_FAILURE';
export const LOADING = 'LOADING';
export const LOAD_DETAIL_CONTACT_SUCCESS = 'LOAD_DETAIL_CONTACT_SUCCESS';
export const LOAD_DETAIL_CONTACT_FAILURE = 'LOAD_DETAIL_CONTACT_FAILURE';
export const LOADING_DETAIL_CONTACT = 'LOADING_DETAIL_CONTACT';
